// Browser-side One Pager PDF generation using jsPDF.
// Matches the visual output of scripts/pdf/generate_one_pager_pdf.py.
// No server call needed — generates directly from report data in memory.

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Thes1s Color Palette (RGB) ──────────────────────────────

const TEAL_500 = [15, 118, 110];
const TEAL_100 = [204, 251, 241];
const TEAL_50 = [240, 253, 250];
const SLATE_800 = [30, 41, 59];
const SLATE_600 = [71, 85, 105];
const SLATE_500 = [100, 116, 139];
const SLATE_200 = [226, 232, 240];
const RED_500 = [239, 68, 68];
const AMBER_500 = [245, 158, 11];
const GREEN_500 = [34, 197, 94];
const WHITE = [255, 255, 255];

function verdictColor(verdict) {
  if (!verdict) return SLATE_600;
  const v = verdict.toUpperCase();
  if (v === 'PASS') return GREEN_500;
  if (v === 'FAIL') return RED_500;
  if (v === 'WATCHLIST' || v === 'REVIEW') return AMBER_500;
  return SLATE_600;
}

function cleanNarrative(text) {
  if (!text) return '';
  return text
    .replace(/<cite[^>]*>(.*?)<\/cite>/gi, '$1')
    .replace(/<cite[^/]*\/>/gi, '')
    .replace(/DataPacket|data packet/gi, 'Thes1s toolbox')
    .replace(/ {2,}/g, ' ')
    .trim();
}

// ─── PDF Generation ──────────────────────────────────────────

export function generateOnePagerPdf(report, sections, ticker, companyName) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  function checkPageBreak(needed = 40) {
    if (y > pageHeight - needed) {
      doc.addPage();
      y = 25;
      addHeader();
    }
  }

  function addHeader() {
    // Teal bar at top
    doc.setFillColor(...TEAL_500);
    doc.rect(0, 0, pageWidth, 3, 'F');
    // Footer
    const pageNum = doc.internal.getNumberOfPages();
    doc.setFontSize(7.5);
    doc.setTextColor(...SLATE_500);
    doc.text(`Thes1s  |  One Pager  |  Page ${pageNum - 1}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // ─── Title Page ────────────────────────────────────────────

  // Teal accent bar
  doc.setFillColor(...TEAL_500);
  doc.rect(0, 0, pageWidth, 6, 'F');

  y = 70;

  // Thes1s branding
  doc.setFontSize(12);
  doc.setTextColor(...TEAL_500);
  doc.setFont('helvetica', 'bold');
  doc.text('Thes1s', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Company name
  doc.setFontSize(28);
  doc.setTextColor(...SLATE_800);
  doc.text(companyName || ticker, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Ticker
  doc.setFontSize(14);
  doc.setTextColor(...SLATE_600);
  doc.setFont('helvetica', 'normal');
  doc.text(`(${ticker})`, pageWidth / 2, y, { align: 'center' });
  y += 16;

  // Teal divider
  doc.setDrawColor(...TEAL_500);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 30, y, pageWidth / 2 + 30, y);
  y += 12;

  // Subtitle
  doc.setFontSize(13);
  doc.setTextColor(...SLATE_800);
  doc.setFont('helvetica', 'bold');
  doc.text('Rule One One Pager', pageWidth / 2, y, { align: 'center' });
  y += 7;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...SLATE_600);
  doc.text('Investment Screening Analysis', pageWidth / 2, y, { align: 'center' });
  y += 20;

  // Overall verdict
  const overallVerdict = sections.find(s => s.key === 'overall_verdict')?.verdict || 'N/A';
  const vc = verdictColor(overallVerdict);
  doc.setFontSize(16);
  doc.setTextColor(...vc);
  doc.setFont('helvetica', 'bold');
  doc.text(overallVerdict, pageWidth / 2, y, { align: 'center' });
  y += 14;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(...SLATE_500);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth / 2, y, { align: 'center' });
  y += 30;

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(...SLATE_500);
  doc.setFont('helvetica', 'italic');
  const disclaimer = 'This report is generated by AI for educational purposes. It is not financial advice. Always do your own research and consult a qualified financial advisor before making investment decisions.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth - 20);
  doc.text(disclaimerLines, pageWidth / 2, y, { align: 'center' });

  // ─── Verdict Scorecard ─────────────────────────────────────

  doc.addPage();
  y = 25;
  addHeader();

  doc.setFontSize(18);
  doc.setTextColor(...TEAL_500);
  doc.setFont('helvetica', 'bold');
  doc.text('Verdict Scorecard', margin, y);
  y += 2;
  doc.setDrawColor(...TEAL_100);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  const scorecardRows = sections.map(s => [
    s.title || s.key,
    s.verdict || 'N/A',
    s.confidence || 'N/A',
    s.redFlags?.length > 0 ? `${s.redFlags.length} flag${s.redFlags.length > 1 ? 's' : ''}` : 'None',
  ]);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Section', 'Verdict', 'Confidence', 'Red Flags']],
    body: scorecardRows,
    headStyles: {
      fillColor: TEAL_500,
      textColor: WHITE,
      fontStyle: 'bold',
      fontSize: 9,
      font: 'helvetica',
    },
    bodyStyles: {
      fontSize: 9,
      textColor: SLATE_800,
      font: 'helvetica',
    },
    alternateRowStyles: {
      fillColor: TEAL_50,
    },
    columnStyles: {
      0: { cellWidth: contentWidth * 0.40 },
      1: { cellWidth: contentWidth * 0.20, halign: 'center' },
      2: { cellWidth: contentWidth * 0.20, halign: 'center' },
      3: { cellWidth: contentWidth * 0.20, halign: 'center' },
    },
    didParseCell: (data) => {
      // Color-code verdict cells
      if (data.column.index === 1 && data.section === 'body') {
        const v = data.cell.raw?.toUpperCase();
        if (v === 'PASS') { data.cell.styles.textColor = GREEN_500; data.cell.styles.fontStyle = 'bold'; }
        else if (v === 'FAIL') { data.cell.styles.textColor = RED_500; data.cell.styles.fontStyle = 'bold'; }
        else if (v === 'WATCHLIST') { data.cell.styles.textColor = AMBER_500; data.cell.styles.fontStyle = 'bold'; }
      }
    },
  });

  y = (doc.lastAutoTable?.finalY || y) + 15;

  // ─── Section Narratives ────────────────────────────────────

  for (const section of sections) {
    checkPageBreak(60);

    // Section header
    doc.setFontSize(14);
    doc.setTextColor(...TEAL_500);
    doc.setFont('helvetica', 'bold');
    doc.text(`${section.sectionNumber || ''}. ${section.title || section.key}`, margin, y);
    y += 2;
    doc.setDrawColor(...TEAL_100);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentWidth, y);
    y += 6;

    // Verdict line
    if (section.verdict) {
      doc.setFontSize(10);
      doc.setTextColor(...verdictColor(section.verdict));
      doc.setFont('helvetica', 'bold');
      doc.text(`Verdict: ${section.verdict}`, margin, y);
      if (section.confidence) {
        doc.setTextColor(...SLATE_600);
        doc.setFont('helvetica', 'normal');
        doc.text(`  |  Confidence: ${section.confidence}`, margin + 45, y);
      }
      y += 6;
    }

    // Verdict rationale
    if (section.verdictRationale) {
      checkPageBreak(20);
      doc.setFontSize(9);
      doc.setTextColor(...SLATE_600);
      doc.setFont('helvetica', 'italic');
      const rationaleLines = doc.splitTextToSize(section.verdictRationale, contentWidth);
      doc.text(rationaleLines, margin, y);
      y += rationaleLines.length * 4 + 4;
    }

    // Narrative
    const narrative = cleanNarrative(
      Array.isArray(section.narrative) ? section.narrative.join('\n\n') : section.narrative
    );
    if (narrative) {
      const paragraphs = narrative.split(/\n\n+/).filter(p => p.trim());
      for (const para of paragraphs) {
        checkPageBreak(20);

        // Check if it's a sub-header (short, ends with colon, or starts with **)
        const isHeader = (para.length < 120 && (para.endsWith(':') || para.match(/^\*\*[^*]+\*\*$/)));
        if (isHeader) {
          doc.setFontSize(10);
          doc.setTextColor(...SLATE_800);
          doc.setFont('helvetica', 'bold');
          const headerText = para.replace(/\*\*/g, '');
          doc.text(headerText, margin, y);
          y += 6;
        } else {
          doc.setFontSize(9);
          doc.setTextColor(...SLATE_800);
          doc.setFont('helvetica', 'normal');
          // Strip bold markers for plain text rendering
          const plainText = para.replace(/\*\*([^*]+)\*\*/g, '$1');
          const lines = doc.splitTextToSize(plainText, contentWidth);
          doc.text(lines, margin, y);
          y += lines.length * 3.8 + 3;
        }
      }
      y += 3;
    }

    // Red Flags
    if (section.redFlags?.length > 0) {
      checkPageBreak(20);
      doc.setFontSize(9);
      doc.setTextColor(...RED_500);
      doc.setFont('helvetica', 'bold');
      doc.text('Red Flags', margin, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...SLATE_800);
      for (const flag of section.redFlags) {
        checkPageBreak(12);
        doc.setFontSize(8.5);
        const flagLines = doc.splitTextToSize(`\u26A0  ${flag}`, contentWidth - 5);
        doc.text(flagLines, margin + 3, y);
        y += flagLines.length * 3.5 + 2;
      }
      y += 3;
    }

    y += 5;
  }

  // ─── Citations ─────────────────────────────────────────────

  const allCitations = sections.flatMap(s => s.citations || []);
  if (allCitations.length > 0) {
    checkPageBreak(40);

    doc.setFontSize(14);
    doc.setTextColor(...TEAL_500);
    doc.setFont('helvetica', 'bold');
    doc.text('Citations & Sources', margin, y);
    y += 2;
    doc.setDrawColor(...TEAL_100);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentWidth, y);
    y += 8;

    doc.setFontSize(8);
    doc.setTextColor(...SLATE_600);
    doc.setFont('helvetica', 'normal');
    doc.text('All quantitative claims are traced to the following sources.', margin, y);
    y += 6;

    for (let i = 0; i < allCitations.length; i++) {
      checkPageBreak(10);
      const c = allCitations[i];
      doc.setFontSize(7.5);
      doc.setTextColor(...SLATE_800);
      doc.setFont('helvetica', 'normal');
      const citText = `[${i + 1}] ${c.text || ''} — ${c.source || 'Unknown source'}`;
      const citLines = doc.splitTextToSize(citText, contentWidth - 5);
      doc.text(citLines, margin + 3, y);
      y += citLines.length * 3 + 1.5;
    }
  }

  // ─── Save ──────────────────────────────────────────────────

  doc.save(`${ticker}-one-pager.pdf`);
}
