// Product Tour step definitions
// FULL_TOUR_STEPS: 14-step walkthrough for new users
// SECTION_TOUR_STEPS: per-section mini tours accessible from ? help button

export const FULL_TOUR_STEPS = [
  {
    id: 'welcome',
    target: null,
    route: null,
    position: 'center',
    title: 'Welcome to Thesis',
    body: "Your AI analyst team is ready. You're the portfolio manager \u2014 Thesis does the 40+ hours of value investing research per company so you can focus on the investment decision. This 60-second tour shows you where everything lives. You can replay it anytime from the ? button in the header.",
  },
  {
    id: 'nav-tabs',
    target: 'nav-tabs',
    route: null,
    position: 'below',
    title: 'Your Navigation',
    body: 'These tabs take you between the four main sections: Watchlists for tracking companies, Research for deep financial analysis, Gurus for seeing what top investors own, and Reports for your AI-generated investment theses.',
  },
  {
    id: 'search-bar',
    target: 'search-bar',
    route: null,
    position: 'below',
    title: 'Search for a Company',
    body: 'Type any ticker symbol or company name to start researching. This opens the Toolbox with 10 years of financial data pulled directly from SEC filings.',
  },
  {
    id: 'company-header',
    target: 'company-header',
    route: '/research/{demoId}',
    position: 'below',
    title: 'Company Overview',
    body: "The header shows the ticker, company name, and current price. The colored score badges on the right \u2014 Thesis Score, Moat, and Management \u2014 are computed from 10 years of SEC EDGAR filings. Green means passing, red means failing. Scores appear after data loads.",
    demoTicker: 'AAPL',
  },
  {
    id: 'score-badges',
    target: 'score-badges',
    route: null,
    position: 'left',
    title: 'Thesis Scores',
    body: 'Three scores at a glance. The overall Thesis Score combines Moat (growth rate quality across BVPS, EPS, revenue, and operating cash flow) and Management (return on equity, return on invested capital, and debt levels). These update automatically as financial data loads.',
  },
  {
    id: 'toolbox-tabs',
    target: 'toolbox-tabs',
    route: null,
    position: 'below',
    title: 'The Toolbox',
    body: 'Seven tabs of financial data: Overview for a quick snapshot, Financials for income statement and balance sheet, Growth for historical rates and charts, Valuation for buy price calculators, Competitors for peer comparison, Insiders for insider trading activity, and Filings for raw SEC documents.',
  },
  {
    id: 'generate-button',
    target: 'generate-button',
    route: null,
    position: 'left',
    title: 'Generate a Report',
    body: 'When you\'re ready for a full analysis, click Generate. Your AI analyst team produces reports in three gated stages: One Pager (quick screen), Pitch Deck (deep research), and Full Story (conviction thesis). Each stage must be approved before the next unlocks.',
  },
  {
    id: 'nav-reports',
    target: 'nav-tab-reports',
    route: '/reports',
    position: 'below',
    title: 'Your Reports',
    body: 'All generated reports live here. Each report shows three stage pills: green means approved, teal means generated and ready for your review, gray means not yet generated, and dimmed means locked until the previous stage is approved.',
  },
  {
    id: 'report-stages',
    target: 'report-card',
    route: null,
    position: 'below',
    title: 'Report Stages',
    body: 'One Pager is a quick AI summary to decide if a company is worth deeper research. Pitch Deck adds 10 deep-dive sections with assumption tracking. Full Story is the comprehensive investment thesis with adversarial bull/bear debate. Approve each stage to unlock the next.',
  },
  {
    id: 'nav-gurus',
    target: 'nav-tab-gurus',
    route: '/gurus',
    position: 'below',
    title: 'Guru Portfolios',
    body: "See what the world's top investors are buying and selling. Data comes from SEC 13F filings, updated quarterly. Use this as context for your research, not as a buy signal \u2014 gurus have different time horizons and strategies.",
  },
  {
    id: 'gurus-tabs',
    target: 'gurus-tabs',
    route: null,
    position: 'below',
    title: 'Guru Views',
    body: 'Latest shows recent buys and sells across all tracked gurus. Directory lists every tracked investor with their portfolio size and top holdings. Stock Lookup lets you search by ticker to see which gurus own a specific company.',
  },
  {
    id: 'nav-watchlists',
    target: 'nav-tab-watchlists',
    route: '/watchlists',
    position: 'below',
    title: 'Watchlists',
    body: "Create watchlists to organize companies you're researching or tracking. Click any ticker in a watchlist to jump straight to its Toolbox.",
  },
  {
    id: 'watchlist-create',
    target: 'watchlist-create',
    route: null,
    position: 'below',
    title: 'Create a Watchlist',
    body: "Click New Watchlist to start organizing. Add tickers with the search field inside each watchlist. You can have multiple watchlists for different strategies \u2014 value picks, growth candidates, sector plays.",
  },
  {
    id: 'settings-gear',
    target: 'settings-gear',
    route: null,
    position: 'left',
    title: "You're All Set",
    body: 'The gear icon opens Settings \u2014 dark mode, display defaults, and data preferences. We left Apple in your Research tab so you have a real company to explore. Go find your first thesis.',
  },
];

export const SECTION_TOUR_STEPS = {
  research: [
    { id: 'res-header', target: 'company-header', route: null, position: 'below',
      title: 'Company Overview', body: 'The header shows ticker, company name, price, and value investing score badges. Green = passing, red = failing.' },
    { id: 'res-scores', target: 'score-badges', route: null, position: 'left',
      title: 'Thesis Scores', body: 'Overall score combines Moat (growth rates) and Management (returns + debt). Computed from 10 years of SEC filings.' },
    { id: 'res-tabs', target: 'toolbox-tabs', route: null, position: 'below',
      title: 'Toolbox Tabs', body: 'Overview, Financials, Growth, Valuation, Competitors, Insiders, and Filings. Each tab pulls data from SEC EDGAR.' },
    { id: 'res-generate', target: 'generate-button', route: null, position: 'left',
      title: 'Generate a Report', body: 'Click Generate to start the AI analysis pipeline. Three stages: One Pager, Pitch Deck, Full Story.' },
  ],
  reports: [
    { id: 'rpt-card', target: 'report-card', route: null, position: 'below',
      title: 'Report Cards', body: 'Each card shows a company with three stage pills. Click any green or teal pill to view that stage.' },
    { id: 'rpt-stages', target: 'report-card', route: null, position: 'below',
      title: 'Stage Pills', body: 'Green = approved. Teal = generated, needs review. Gray = not generated. Dimmed = locked (previous stage not approved).' },
  ],
  gurus: [
    { id: 'guru-tabs', target: 'gurus-tabs', route: null, position: 'below',
      title: 'Guru Tabs', body: 'Latest for recent activity, Directory for all tracked investors, Stock Lookup to search by ticker.' },
  ],
  watchlists: [
    { id: 'wl-create', target: 'watchlist-create', route: null, position: 'below',
      title: 'New Watchlist', body: 'Click to create a new watchlist. Add tickers with the search field inside each one.' },
  ],
};
